name: Generate Packages

'on':
  push:
    branches:
    - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  packages-list:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ env.packages }}
    steps:
      - uses: actions/checkout@v4
      - run: |-
          echo "packages=$(echo $(cat packages.json))" >> ${GITHUB_ENV}
  build:
    runs-on: ubuntu-latest
    needs:
      - packages-list
    strategy:
      matrix: ${{fromJson(needs.packages-list.outputs.packages)}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: ${{ matrix.package.repository }}
          ref: ${{ matrix.package.ref }}
          path: foreign
      - uses: actions/checkout@v4
        with:
          ref: tracking
          path: tracking
      - run: |
          foreign_sha="$(cd foreign && git rev-parse HEAD)"
          echo "$foreign_sha"
          continue="true"
          if [ -f "tracking/${{ matrix.package.name }}.sha" ]; then
            current_sha="$(cat tracking/${{ matrix.package.name }}.sha)"
            echo "$current_sha"
            if [[ "$foreign_sha" == "$current_sha" ]]; then
              echo "SHAs match! No changes necessary."
              continue="false"
            fi
          fi
          mkdir -p "sha/${{ matrix.package.outputPath }}"
          echo "continue=$shas_match" >> $GITHUB_ENV
          echo "$foreign_sha" > "sha/${{ matrix.package.name }}.sha"
      - name: Upload artifact
        if: env.continue == "false"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package.shaArtifactName }}
          path: sha/
      - uses: actions/setup-python@v5
        if: env.continue == "false"
        with:
          python-version: '3.13'
      - name: Install generator
        if: env.continue == "false"
        run: | 
          pip install pkl-github-actions-step-generator==0.1.13
          mkdir output
      - name: Build package
        if: env.continue == "false"
        run: |
          pkl-github-actions-step-generator from-remote "${{ matrix.package.name }}" \
            ${{ matrix.package.deprecated && '--deprecated' || '' }} \
            -o "output/action.pkl" \
            --generate-pklproject \
            --package-baseuri "emilym.cl/pkl-github-actions-packages/${{ matrix.package.name }}" \
            --package-output "output/PklProject" \
            --yaml-constraints-file "constraints.yml" \
            --package-version "${{ matrix.package.version }}"
      - name: Install pkl
        if: env.continue == "false"
        uses: pkl-community/setup-pkl@v0
        with:
          pkl-version: 0.27.0
      - name: Package Pkl
        if: env.continue == "false"
        run: | 
          mkdir -p "pkg/${{ matrix.package.outputPath }}"
          pkl project package --skip-publish-check ./output
          sed -i "s|pkl-github-actions-packages/${{ matrix.package.name }}/|pkl-github-actions-packages/|g" "${{ matrix.package.buildPath }}/${{ matrix.package.packageName }}"
          mv ${{ matrix.package.buildPath }}* "pkg/${{ matrix.package.outputPath }}"
      - name: Upload artifact
        if: env.continue == "false"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package.artifactName }}
          path: pkg
  publish:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      contents: write
    needs: 
      - build
    steps:
      - uses: actions/checkout@v4
        with:
          path: pages
          ref: gh-pages
      - uses: actions/checkout@v4
        with:
          path: tracking
          ref: tracking
      - run: mkdir artifacts shas
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: package_*
      - uses: actions/download-artifact@v4
        with:
          path: shas
          pattern: sha_*
      - run: | 
          rsync -av artifacts/*/ pages/
          rsync -av shas/*/ tracking/
          ls -lR pages/
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./pages
          commit_message: "Update packages"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./tracking
          commit_message: "Update shas"
    
